[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Major-Group-51"
version = "0.1.0"
description = "A brief description of your project."
requires-python = ">=3.10"

authors = [
    { name = "Shreya Srivastava" },
    { name = "Aditya Singh" },
    { name = "Dinesh Dhiman" },
    { name = "Arshit Dogra" }
]

readme = "README.md"
license = { file = "LICENSE" }

urls = { "Homepage" = "https://github.com/Fairtexas5/Major_Grp51" }

dependencies = [
  "requests>=2.32.5",
  "numpy>=2.3.3",
  "keras>=3.11.3",
  "matplotlib>=3.10.6",
  "tensorflow>=2.20.0",
  "torch>=2.8.0",
  "pandas>=2.3.2",
  "ipython-autotime>=0.3.2",
  "openai",
  "anthropic>=0.68.0",
  "transformers>=4.56.2",
  "scikit-learn>=1.7.2",
  "shap>=0.48.0",
  "lime>=0.2.0.1",
  "openai>=1.108.1",
  "seaborn>=0.13.2",
  "poetry>=2.2.1"
]
