[project]
name = "major-grp51"
version = "2.1.4"
description = "Fine-Tuning LLMs for Detecting HRVs"

authors = [
    { name = "Shreya Srivastava" },
    { name = "Aditya Singh" },
    { name = "Dinesh Dhiman" },
    { name = "Arshit Dogra" }
]
license = { file = "LICENSE" }
urls = { "Homepage" = "https://github.com/Fairtexas5/Major_Grp51" }

readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argostranslate>=1.11.0",
    "gradio>=6.14.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "pandas>=3.0.2",
    "plotly>=6.7.0",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.3",
]
